In [1]:
import numpy as np

# Creating the arrays
array_1 = np.random.rand(3, 4)  # Array with shape (3, 4)
array_2 = np.random.rand(4)      # Array with shape (4,)

# Broadcasting
result = array_1 + array_2

print("Broadcasted Result:\n", result)


Broadcasted Result:
 [[0.93821146 1.16734004 1.32004327 0.54154657]
 [0.62224278 1.25803724 0.98436263 0.67943061]
 [0.80647872 0.80463318 1.14974203 1.34063781]]


In [2]:
# Creating a 2D array with shape (5, 5)
array_2d = np.random.randint(1, 10, size=(5, 5))

# Extracting diagonal elements
diagonal_elements = array_2d[np.diag_indices_from(array_2d)]

# Extracting elements greater than 3
greater_than_3 = array_2d[array_2d > 3]

print("Diagonal Elements:\n", diagonal_elements)
print("Elements greater than 3:\n", greater_than_3)


Diagonal Elements:
 [6 3 1 3 8]
Elements greater than 3:
 [6 8 9 7 8 7 6 5 7 4 4 9 6 8 8]


In [3]:
# Creating a 2D array with shape (4, 5)
array_2d = np.random.randint(1, 10, size=(4, 5))

# Inserting a new row at index 2
new_row = np.array([10, 20, 30, 40, 50])
array_with_inserted_row = np.insert(array_2d, 2, new_row, axis=0)

# Deleting the last column
array_with_deleted_column = np.delete(array_with_inserted_row, -1, axis=1)

print("Array with Inserted Row:\n", array_with_inserted_row)
print("Array with Deleted Last Column:\n", array_with_deleted_column)


Array with Inserted Row:
 [[ 2  4  6  8  9]
 [ 3  7  1  8  6]
 [10 20 30 40 50]
 [ 6  3  5  1  9]
 [ 6  1  5  4  9]]
Array with Deleted Last Column:
 [[ 2  4  6  8]
 [ 3  7  1  8]
 [10 20 30 40]
 [ 6  3  5  1]
 [ 6  1  5  4]]


In [4]:
# Matrix multiplication
array_1 = np.random.rand(3, 4)
array_2 = np.random.rand(4, 2)
matrix_multiplication_result = np.matmul(array_1, array_2)

# Determinant and Inverse
square_matrix = np.random.rand(3, 3)
determinant = np.linalg.det(square_matrix)
inverse = np.linalg.inv(square_matrix)

print("Matrix Multiplication Result:\n", matrix_multiplication_result)
print("Determinant:\n", determinant)
print("Inverse:\n", inverse)


Matrix Multiplication Result:
 [[0.42953112 0.62591526]
 [1.03601125 0.69586927]
 [1.04315702 0.98237669]]
Determinant:
 -0.08531444771612266
Inverse:
 [[ 5.09439936  0.42688314 -1.98771882]
 [-3.76139988 -0.57065352  2.64568011]
 [-6.61493338  1.48941436  2.16294641]]


In [5]:
# Generating a 2D array from a normal distribution
random_normal_array = np.random.randn(5, 5)

# Generating a 1D array with random integers
random_integers_array = np.random.randint(1, 11, size=10)

print("Random Normal Array:\n", random_normal_array)
print("Random Integers Array:\n", random_integers_array)


Random Normal Array:
 [[ 0.17024984  0.28931773 -0.35542669 -0.88941446  1.0386206 ]
 [-1.90244957 -0.65123802 -0.19022254 -1.4377865  -0.58495279]
 [ 0.08697267  1.07511204 -1.03710647  2.69013495  0.51241775]
 [ 1.64391944  0.29718507 -0.88272398 -0.58747741  0.58029006]
 [-0.67832438  0.20264198 -0.55202472  0.84148019  0.6828424 ]]
Random Integers Array:
 [2 5 5 4 8 5 6 2 2 6]


In [6]:
import time

# Element-wise operation using Numpy (Vectorized)
array_large = np.random.rand(1000000)
start_time = time.time()
result_vectorized = array_large * 2
end_time = time.time()
vectorized_time = end_time - start_time

# Element-wise operation using Python's built-in loops
start_time = time.time()
result_loop = [x * 2 for x in array_large]
end_time = time.time()
loop_time = end_time - start_time

print("Time taken by vectorized operation: {:.6f} seconds".format(vectorized_time))
print("Time taken by loop operation: {:.6f} seconds".format(loop_time))


Time taken by vectorized operation: 0.002947 seconds
Time taken by loop operation: 0.090278 seconds
