In [3]:
import numpy as np

# Create a 2D array 'a' with shape (3, 4) containing random integers
a_2d = np.random.randint(1, 100, size=(3, 4))
print("2D Array 'a_2d':")
print(a_2d)

# Create arrays 'rows' and 'cols' containing indices
rows_array = np.array([0, 1, 2])
cols_array = np.array([1, 2, 3])
print("\nRows Array 'rows_array':", rows_array)
print("Cols Array 'cols_array':", cols_array)

# Use fancy indexing to extract elements from 'a' using 'rows' and 'cols'
extracted_elements_array = a_2d[rows_array, cols_array]
print("\nExtracted Elements using Arrays:")
print(extracted_elements_array)



2D Array 'a_2d':
[[56 86 31 59]
 [12 11 97 45]
 [12 43 32 77]]

Rows Array 'rows_array': [0 1 2]
Cols Array 'cols_array': [1 2 3]

Extracted Elements using Arrays:
[86 97 77]


In [4]:
# Create a 1D array 'a' containing integers from 1 to 10
a_1d = np.arange(1, 11)
print("\n1D Array 'a_1d':", a_1d)

# Create a boolean mask 'mask' to select elements greater than 5
mask = a_1d > 5
print("Boolean Mask 'mask':", mask)

# Use fancy indexing to extract elements from 'a' using 'mask'
extracted_elements_boolean = a_1d[mask]
print("\nExtracted Elements using Boolean Mask:")
print(extracted_elements_boolean)



1D Array 'a_1d': [ 1  2  3  4  5  6  7  8  9 10]
Boolean Mask 'mask': [False False False False False  True  True  True  True  True]

Extracted Elements using Boolean Mask:
[ 6  7  8  9 10]


In [5]:
# Create a 2D array 'a' with shape (3, 4) containing random integers
a_2d_list = np.random.randint(1, 100, size=(3, 4))
print("\n2D Array 'a_2d_list':")
print(a_2d_list)

# Create two lists 'rows' and 'cols' containing indices
rows_list = [0, 1, 2]
cols_list = [0, 2, 3]
print("\nRows List 'rows_list':", rows_list)
print("Cols List 'cols_list':", cols_list)

# Use fancy indexing to extract elements from 'a' using 'rows' and 'cols'
extracted_elements_list = a_2d_list[rows_list, cols_list]
print("\nExtracted Elements using Lists:")
print(extracted_elements_list)



2D Array 'a_2d_list':
[[20 38 29 76]
 [58 39  7 59]
 [67 50 59 70]]

Rows List 'rows_list': [0, 1, 2]
Cols List 'cols_list': [0, 2, 3]

Extracted Elements using Lists:
[20  7 70]


In [6]:
# Create a 3D array 'a' with shape (2, 3, 4) containing random integers
a_3d = np.random.randint(1, 100, size=(2, 3, 4))
print("\n3D Array 'a_3d':")
print(a_3d)

# Use fancy indexing to extract elements from 'a' using arrays of indices
rows_3d = np.array([0, 1])
cols_3d = np.array([1, 2])
depths_3d = np.array([0, 3])
print("\nRows Array 'rows_3d':", rows_3d)
print("Cols Array 'cols_3d':", cols_3d)
print("Depths Array 'depths_3d':", depths_3d)

extracted_elements_3d = a_3d[rows_3d[:, None], cols_3d[:, None], depths_3d]
print("\nExtracted Elements using Advanced Fancy Indexing:")
print(extracted_elements_3d)



3D Array 'a_3d':
[[[ 3 35  4 83]
  [48 81 42 22]
  [55 80 99 75]]

 [[88  5 62 25]
  [13  7 55 71]
  [28 26 42 76]]]

Rows Array 'rows_3d': [0 1]
Cols Array 'cols_3d': [1 2]
Depths Array 'depths_3d': [0 3]

Extracted Elements using Advanced Fancy Indexing:
[[48 22]
 [28 76]]


In [2]:
import numpy as np

# Create a 2D array 'a' with shape (3, 4) containing random integers
a_2d = np.random.randint(1, 100, size=(3, 4))

# Create arrays 'rows' and 'cols' containing indices
rows_array = np.array([0, 1, 2])
cols_array = np.array([1, 2, 3])

# Use fancy indexing to extract elements from 'a' using 'rows' and 'cols'
extracted_elements_array = a_2d[rows_array, cols_array]
print(extracted_elements_array)


[94 91  1]


In [6]:
# Create a 1D array 'a' containing integers from 1 to 10
a_1d = np.arange(1, 11)

# Create a boolean mask 'mask' to select elements greater than 5
mask = a_1d > 5

# Use fancy indexing to extract elements from 'a' using 'mask'
extracted_elements_boolean = a_1d[mask]
print(extracted_elements_boolean)

[ 6  7  8  9 10]


In [8]:
# Create a 2D array 'a' with shape (3, 4) containing random integers
a_2d_list = np.random.randint(1, 100, size=(3, 4))

# Create two lists 'rows' and 'cols' containing indices
rows_list = [0, 1, 2]
cols_list = [0, 2, 3]

# Use fancy indexing to extract elements from 'a' using 'rows' and 'cols'
extracted_elements_list = a_2d_list[rows_list, cols_list]
print(extracted_elements_list)

[70 23 93]


In [7]:
# Create a 3D array 'a' with shape (2, 3, 4) containing random integers
a_3d = np.random.randint(1, 100, size=(2, 3, 4))

# Use fancy indexing to extract elements from 'a' using arrays of indices
rows_3d = np.array([0, 1])
cols_3d = np.array([1, 2])
depths_3d = np.array([0, 3])

extracted_elements_3d = a_3d[rows_3d[:, None], cols_3d[:, None], depths_3d]
print(extracted_elements_3d)

[[13 26]
 [67 16]]
